// Namma Ooru — content for the map.
// Positions are neighbourhood-level, never street addresses.
//   prec: "area"  → placed in the named area (reported publicly as the company's base)
//         "city"  → Bengaluru presence, exact area unstated → shown in a cluster near the CBD
//         "none"  → no Bengaluru office on the board; appears in the Network view only
// Edit freely — every panel, count and graph is derived from this file.

window.NO = window.NO || {};

// Map extent (degrees). Kempegowda International Airport sits ~20 km north of this edge.
NO.BBOX = { s: 12.83, w: 77.46, n: 13.11, e: 77.80 };

NO.AREAS = {
  cbd:          { name: "MG Road & CBD",       lat: 12.9745, lon: 77.6060 },
  koramangala:  { name: "Koramangala",         lat: 12.9352, lon: 77.6245 },
  indiranagar:  { name: "Indiranagar",         lat: 12.9719, lon: 77.6412 },
  hsr:          { name: "HSR Layout",          lat: 12.9116, lon: 77.6474 },
  orr:          { name: "Bellandur · ORR",     lat: 12.9290, lon: 77.6800 },
  marathahalli: { name: "Marathahalli",        lat: 12.9569, lon: 77.7011 },
  whitefield:   { name: "Whitefield",          lat: 12.9780, lon: 77.7380 },
  ecity:        { name: "Electronic City",     lat: 12.8452, lon: 77.6602 },
  jpnagar:      { name: "JP Nagar",            lat: 12.9063, lon: 77.5857 },
  jayanagar:    { name: "Jayanagar",           lat: 12.9250, lon: 77.5938 },
  basavanagudi: { name: "Basavanagudi",        lat: 12.9420, lon: 77.5720 },
  bannerghatta: { name: "Bannerghatta Road",   lat: 12.8990, lon: 77.5990 },
  btm:          { name: "BTM Layout",          lat: 12.9166, lon: 77.6101 },
  domlur:       { name: "Domlur",              lat: 12.9546, lon: 77.6390 },
  malleshwaram: { name: "Malleshwaram",        lat: 13.0035, lon: 77.5700 },
  rajajinagar:  { name: "Rajajinagar",         lat: 12.9900, lon: 77.5525 },
  yeshwanthpur: { name: "Yeshwanthpur",        lat: 13.0280, lon: 77.5400 },
  hebbal:       { name: "Hebbal",              lat: 13.0358, lon: 77.5970 },
  manyata:      { name: "Manyata · Nagawara",  lat: 13.0450, lon: 77.6210 },
  cvraman:      { name: "CV Raman Nagar",      lat: 12.9806, lon: 77.6621 },
  krpuram:      { name: "KR Puram",            lat: 13.0050, lon: 77.6960 },
  sarjapur:     { name: "Sarjapur Road",       lat: 12.9120, lon: 77.6880 },
  banashankari: { name: "Banashankari",        lat: 12.9255, lon: 77.5468 },
  yelahanka:    { name: "Yelahanka",           lat: 13.1005, lon: 77.5963 },
  jalahalli:    { name: "Jalahalli",           lat: 13.0450, lon: 77.5450 },
  mysoreroad:   { name: "Mysore Road",         lat: 12.9200, lon: 77.4990 },
  majestic:     { name: "Majestic",            lat: 12.9774, lon: 77.5713 },
  oldairport:   { name: "Old Airport Road",    lat: 12.9590, lon: 77.6560 },
};

// Filter groups — order is the order shown in the panel.
NO.GROUPS = [
  { id: "companies", label: "Companies", cats: [
    { id: "commerce",  label: "Commerce & delivery", color: "#e2572b" },
    { id: "fintech",   label: "Fintech",             color: "#d99a06" },
    { id: "mobility",  label: "Mobility & EV",       color: "#6aa312" },
    { id: "deeptech",  label: "AI, SaaS & deeptech", color: "#2f8fbf" },
    { id: "consumer",  label: "Health, learning & consumer", color: "#c2417a" },
  ]},
  { id: "capital", label: "Capital", cats: [
    { id: "vc",        label: "Venture capital",     color: "#1f9e74" },
    { id: "angel",     label: "Angel network",       color: "#58b88f" },
    { id: "strategic", label: "Strategic investor",  color: "#2e7d6b" },
  ]},
  { id: "institutions", label: "Institutions", cats: [
    { id: "univ",      label: "University & research", color: "#6b4fc4" },
    { id: "incubator", label: "Incubator & accelerator", color: "#8f67e0" },
    { id: "techpark",  label: "Tech park",           color: "#4d6bd6" },
    { id: "cowork",    label: "Coworking",           color: "#b25ad0" },
  ]},
  { id: "other", label: "Other bodies", cats: [
    { id: "corporate", label: "Global R&D & corporates", color: "#7a7f86" },
    { id: "public",    label: "Public body",         color: "#9a8a5c" },
  ]},
];

// id, name, cat, area, prec, year, blurb, backers (ids of capital orgs)
NO.ORGS = [
  // ── Commerce & delivery
  { id:"flipkart", name:"Flipkart", cat:"commerce", area:"orr", prec:"area", year:2007,
    blurb:"Started in a Koramangala flat selling books; became India's largest e-commerce marketplace. Walmart bought a majority stake in 2018.",
    backers:["accel","tiger","softbank","walmart"] },
  { id:"swiggy", name:"Swiggy", cat:"commerce", area:"orr", prec:"area", year:2014,
    blurb:"Food delivery that grew out of Koramangala, then quick-commerce with Instamart. Listed on Indian exchanges in 2024.",
    backers:["accel","elevation","prosus","softbank"] },
  { id:"meesho", name:"Meesho", cat:"commerce", area:"orr", prec:"area", year:2015,
    blurb:"Social-commerce marketplace built for small sellers and value-conscious buyers beyond the metros.",
    backers:["yc","peakxv","elevation","prosus","softbank","meta"] },
  { id:"myntra", name:"Myntra", cat:"commerce", area:"hsr", prec:"area", year:2007,
    blurb:"Fashion e-commerce; acquired by Flipkart in 2014.",
    backers:["flipkart"] },
  { id:"bigbasket", name:"BigBasket", cat:"commerce", area:"domlur", prec:"city", year:2011,
    blurb:"Online grocer; majority owned by Tata Digital since 2021.",
    backers:["tatadigital"] },
  { id:"udaan", name:"Udaan", cat:"commerce", area:"oldairport", prec:"city", year:2016,
    blurb:"B2B trade platform connecting small retailers with brands and wholesalers.",
    backers:["lightspeed","dst"] },
  { id:"dunzo", name:"Dunzo", cat:"commerce", area:"koramangala", prec:"city", year:2014,
    blurb:"Started as a WhatsApp group that would fetch anything across the city. A very Bengaluru idea.",
    backers:["blume","google","reliance"] },
  { id:"licious", name:"Licious", cat:"commerce", area:"koramangala", prec:"city", year:2015,
    blurb:"Direct-to-consumer fresh meat and seafood brand.",
    backers:["threeone4","temasek"] },
  { id:"zetwerk", name:"Zetwerk", cat:"commerce", area:"cbd", prec:"city", year:2018,
    blurb:"Manufacturing network for contract production across India.",
    backers:["peakxv"] },

  // ── Fintech
  { id:"phonepe", name:"PhonePe", cat:"fintech", area:"orr", prec:"area", year:2015,
    blurb:"UPI payments app, among the biggest by transaction volume. Part of Walmart's group via Flipkart.",
    backers:["walmart","generalatlantic","tiger"] },
  { id:"razorpay", name:"Razorpay", cat:"fintech", area:"koramangala", prec:"area", year:2014,
    blurb:"Payments infrastructure for Indian businesses. A Y Combinator alumnus.",
    backers:["yc","peakxv","tiger","ribbit","gic"] },
  { id:"cred", name:"CRED", cat:"fintech", area:"indiranagar", prec:"city", year:2018,
    blurb:"Members-only credit card bill payments and rewards, known for its ads.",
    backers:["peakxv","tiger","dst"] },
  { id:"zerodha", name:"Zerodha", cat:"fintech", area:"jpnagar", prec:"area", year:2010,
    blurb:"India's biggest discount stockbroker, built without venture capital. Its investor list is intentionally empty.",
    backers:[] },
  { id:"groww", name:"Groww", cat:"fintech", area:"orr", prec:"area", year:2016,
    blurb:"Investing app for mutual funds and stocks, aimed at first-time investors.",
    backers:["yc","peakxv","tiger","ribbit"] },
  { id:"juspay", name:"Juspay", cat:"fintech", area:"koramangala", prec:"area", year:2012,
    blurb:"Payments orchestration behind many of India's largest checkouts, and early UPI infrastructure.",
    backers:["accel"] },
  { id:"khatabook", name:"Khatabook", cat:"fintech", area:"hsr", prec:"city", year:2018,
    blurb:"Digital ledger for small shopkeepers, replacing the paper khata book.",
    backers:["peakxv"] },
  { id:"slice", name:"slice", cat:"fintech", area:"koramangala", prec:"city", year:2016,
    blurb:"Payments and credit for young users.",
    backers:["tiger","insight"] },
  { id:"smallcase", name:"smallcase", cat:"fintech", area:"koramangala", prec:"city", year:2015,
    blurb:"Themed baskets of stocks and ETFs sold through brokers.",
    backers:["peakxv","rainmatter"] },
  { id:"acko", name:"Acko", cat:"fintech", area:"koramangala", prec:"city", year:2016,
    blurb:"Digital-first general insurer.",
    backers:["accel","amazon","generalatlantic"] },
  { id:"digit", name:"Go Digit", cat:"fintech", area:"koramangala", prec:"city", year:2016,
    blurb:"General insurer backed by Fairfax.",
    backers:["fairfax"] },
  { id:"setu", name:"Setu", cat:"fintech", area:"indiranagar", prec:"city", year:2018,
    blurb:"APIs for India's financial rails. Acquired by Pine Labs in 2022.",
    backers:["lightspeed"] },

  // ── Mobility & EV
  { id:"ola", name:"Ola", cat:"mobility", area:"koramangala", prec:"area", year:2010,
    blurb:"Ride-hailing that put Bengaluru's autos onto an app.",
    backers:["z47","tiger","softbank"] },
  { id:"olaelectric", name:"Ola Electric", cat:"mobility", area:"koramangala", prec:"area", year:2017,
    blurb:"Electric scooters; the factory is in Krishnagiri, Tamil Nadu. Listed in 2024.",
    backers:["z47","tiger","softbank"] },
  { id:"rapido", name:"Rapido", cat:"mobility", area:"koramangala", prec:"area", year:2015,
    blurb:"Bike taxis that zip through traffic. Now also autos and cabs.",
    backers:["westbridge","swiggy"] },
  { id:"ather", name:"Ather Energy", cat:"mobility", area:"malleshwaram", prec:"city", year:2013,
    blurb:"Electric scooters designed in Bengaluru, started by IIT Madras graduates.",
    backers:["tiger","hero"] },
  { id:"yulu", name:"Yulu", cat:"mobility", area:"indiranagar", prec:"city", year:2017,
    blurb:"The small blue electric bikes parked outside every metro station.",
    backers:["bajaj","magna"] },

  // ── AI, SaaS & deeptech
  { id:"postman", name:"Postman", cat:"deeptech", area:"indiranagar", prec:"city", year:2014,
    blurb:"API development platform used by millions of developers. Began as a side project.",
    backers:["nexus","insight"] },
  { id:"sarvam", name:"Sarvam AI", cat:"deeptech", area:"indiranagar", prec:"city", year:2023,
    blurb:"Foundation models built for Indian languages.",
    backers:["lightspeed","peakxv","khosla"] },
  { id:"inmobi", name:"InMobi", cat:"deeptech", area:"orr", prec:"area", year:2007,
    blurb:"Mobile advertising, and the parent of Glance.",
    backers:["softbank"] },
  { id:"hasura", name:"Hasura", cat:"deeptech", area:"indiranagar", prec:"city", year:2017,
    blurb:"Instant GraphQL APIs over your data.",
    backers:["nexus"] },
  { id:"krutrim", name:"Krutrim", cat:"deeptech", area:"koramangala", prec:"city", year:2023,
    blurb:"AI models and cloud from the Ola group.",
    backers:[] },
  { id:"sharechat", name:"ShareChat", cat:"deeptech", area:"hsr", prec:"city", year:2015,
    blurb:"Social media in Indian languages, and the short-video app Moj.",
    backers:["lightspeed","tiger"] },

  // ── Health, learning & consumer
  { id:"byjus", name:"BYJU'S", cat:"consumer", area:"bannerghatta", prec:"area", year:2011,
    blurb:"Edtech that grew from a teacher's classes into a global brand, followed by a much-reported collapse.",
    backers:["lightspeed","peakxv","prosus"] },
  { id:"unacademy", name:"Unacademy", cat:"consumer", area:"hsr", prec:"city", year:2015,
    blurb:"Online test prep that started as a YouTube channel.",
    backers:["blume","peakxv","softbank","generalatlantic"] },
  { id:"vedantu", name:"Vedantu", cat:"consumer", area:"hsr", prec:"city", year:2011,
    blurb:"Live online tutoring.",
    backers:["accel"] },
  { id:"cultfit", name:"cult.fit", cat:"consumer", area:"hsr", prec:"city", year:2016,
    blurb:"Gyms, group workouts and a fitness app.",
    backers:["accel","chiratae","tatadigital"] },
  { id:"practo", name:"Practo", cat:"consumer", area:"bannerghatta", prec:"city", year:2008,
    blurb:"Doctor discovery, appointments and online consultations.",
    backers:["peakxv","tencent"] },
  { id:"ultrahuman", name:"Ultrahuman", cat:"consumer", area:"indiranagar", prec:"city", year:2019,
    blurb:"Smart rings and metabolic health wearables.",
    backers:["blume"] },

  // ── Venture capital (Bengaluru offices)
  { id:"accel", name:"Accel", cat:"vc", area:"cbd", prec:"city", blurb:"Early-stage VC; led Flipkart's first venture round.", backers:[] },
  { id:"peakxv", name:"Peak XV Partners", cat:"vc", area:"cbd", prec:"city", blurb:"Formerly Sequoia Capital India & SEA; runs the Surge programme.", backers:[] },
  { id:"lightspeed", name:"Lightspeed India", cat:"vc", area:"cbd", prec:"city", blurb:"Multi-stage VC with a large Bengaluru team.", backers:[] },
  { id:"elevation", name:"Elevation Capital", cat:"vc", area:"cbd", prec:"city", blurb:"Formerly SAIF Partners India.", backers:[] },
  { id:"kalaari", name:"Kalaari Capital", cat:"vc", area:"cbd", prec:"city", blurb:"Bengaluru-headquartered early-stage fund.", backers:[] },
  { id:"blume", name:"Blume Ventures", cat:"vc", area:"cbd", prec:"city", blurb:"Seed and early-stage fund.", backers:[] },
  { id:"nexus", name:"Nexus Venture Partners", cat:"vc", area:"cbd", prec:"city", blurb:"Early-stage fund across India and the US.", backers:[] },
  { id:"z47", name:"Z47", cat:"vc", area:"cbd", prec:"city", blurb:"Formerly Matrix Partners India; Ola's first institutional investor.", backers:[] },
  { id:"chiratae", name:"Chiratae Ventures", cat:"vc", area:"cbd", prec:"city", blurb:"Formerly IDG Ventures India.", backers:[] },
  { id:"stellaris", name:"Stellaris Venture Partners", cat:"vc", area:"cbd", prec:"city", blurb:"Early-stage fund.", backers:[] },
  { id:"threeone4", name:"3one4 Capital", cat:"vc", area:"cbd", prec:"city", blurb:"Early-stage fund.", backers:[] },
  { id:"westbridge", name:"WestBridge Capital", cat:"vc", area:"cbd", prec:"city", blurb:"Growth investor.", backers:[] },
  { id:"prime", name:"Prime Venture Partners", cat:"vc", area:"cbd", prec:"city", blurb:"Early-stage fund.", backers:[] },
  { id:"rainmatter", name:"Rainmatter", cat:"vc", area:"jpnagar", prec:"city", blurb:"Zerodha's investment arm for fintech, climate and health.", backers:[] },

  // ── Angel networks
  { id:"letsventure", name:"LetsVenture", cat:"angel", area:"cbd", prec:"city", blurb:"Online platform for angel investing.", backers:[] },
  { id:"ian", name:"Indian Angel Network", cat:"angel", area:"cbd", prec:"city", blurb:"Angel network with a Bengaluru chapter.", backers:[] },

  // ── Strategic & off-board investors (network view only)
  { id:"tiger", name:"Tiger Global", cat:"strategic", prec:"none", blurb:"New York crossover fund; very active in India in 2020–21.", backers:[] },
  { id:"softbank", name:"SoftBank", cat:"strategic", prec:"none", blurb:"Tokyo; Vision Fund.", backers:[] },
  { id:"yc", name:"Y Combinator", cat:"strategic", prec:"none", blurb:"San Francisco accelerator.", backers:[] },
  { id:"prosus", name:"Prosus", cat:"strategic", prec:"none", blurb:"Amsterdam; formerly Naspers' internet arm.", backers:[] },
  { id:"walmart", name:"Walmart", cat:"strategic", prec:"none", blurb:"Majority owner of Flipkart and PhonePe's group.", backers:[] },
  { id:"dst", name:"DST Global", cat:"strategic", prec:"none", blurb:"Growth investor.", backers:[] },
  { id:"ribbit", name:"Ribbit Capital", cat:"strategic", prec:"none", blurb:"Fintech-focused fund.", backers:[] },
  { id:"gic", name:"GIC", cat:"strategic", prec:"none", blurb:"Singapore sovereign fund.", backers:[] },
  { id:"temasek", name:"Temasek", cat:"strategic", prec:"none", blurb:"Singapore investment company.", backers:[] },
  { id:"generalatlantic", name:"General Atlantic", cat:"strategic", prec:"none", blurb:"Growth equity.", backers:[] },
  { id:"insight", name:"Insight Partners", cat:"strategic", prec:"none", blurb:"Software-focused growth fund.", backers:[] },
  { id:"tencent", name:"Tencent", cat:"strategic", prec:"none", blurb:"Shenzhen.", backers:[] },
  { id:"khosla", name:"Khosla Ventures", cat:"strategic", prec:"none", blurb:"Menlo Park.", backers:[] },
  { id:"google", name:"Google", cat:"strategic", prec:"none", blurb:"Strategic investment.", backers:[] },
  { id:"reliance", name:"Reliance Retail", cat:"strategic", prec:"none", blurb:"Strategic investment.", backers:[] },
  { id:"meta", name:"Meta", cat:"strategic", prec:"none", blurb:"Strategic investment.", backers:[] },
  { id:"amazon", name:"Amazon", cat:"strategic", prec:"none", blurb:"Strategic investment.", backers:[] },
  { id:"fairfax", name:"Fairfax", cat:"strategic", prec:"none", blurb:"Toronto; Prem Watsa's holding company.", backers:[] },
  { id:"hero", name:"Hero MotoCorp", cat:"strategic", prec:"none", blurb:"Two-wheeler maker.", backers:[] },
  { id:"bajaj", name:"Bajaj Auto", cat:"strategic", prec:"none", blurb:"Two-wheeler maker.", backers:[] },
  { id:"magna", name:"Magna International", cat:"strategic", prec:"none", blurb:"Auto components.", backers:[] },
  { id:"tatadigital", name:"Tata Digital", cat:"strategic", prec:"none", blurb:"Tata group's consumer tech arm.", backers:[] },

  // ── Universities & research
  { id:"iisc", name:"IISc", cat:"univ", area:"malleshwaram", prec:"area", year:1909,
    blurb:"Indian Institute of Science, founded with Jamsetji Tata's support; its 400-acre campus is locally called 'Tata Institute'.", backers:[], lat:13.0219, lon:77.5671 },
  { id:"iimb", name:"IIM Bangalore", cat:"univ", area:"bannerghatta", prec:"area", year:1973,
    blurb:"Business school on Bannerghatta Road, in stone buildings designed by B. V. Doshi.", backers:[], lat:12.8950, lon:77.6010 },
  { id:"iiitb", name:"IIIT Bangalore", cat:"univ", area:"ecity", prec:"area", year:1999,
    blurb:"IT research institute in Electronic City.", backers:[], lat:12.8446, lon:77.6630 },
  { id:"ncbs", name:"NCBS · Bangalore Life Science Cluster", cat:"univ", area:"hebbal", prec:"area",
    blurb:"Biology research campus on Bellary Road; home of the C-CAMP bio-incubator.", backers:[], lat:13.0716, lon:77.5800 },

  // ── Incubators & accelerators
  { id:"nsrcel", name:"NSRCEL", cat:"incubator", area:"bannerghatta", prec:"area", year:2002,
    blurb:"IIM Bangalore's startup hub.", backers:[], lat:12.8960, lon:77.6000 },
  { id:"sid", name:"SID · IISc", cat:"incubator", area:"malleshwaram", prec:"area",
    blurb:"Society for Innovation and Development, IISc's incubator for deeptech.", backers:[], lat:13.0200, lon:77.5690 },
  { id:"ccamp", name:"C-CAMP", cat:"incubator", area:"hebbal", prec:"area",
    blurb:"Centre for Cellular and Molecular Platforms, a biotech incubator.", backers:[], lat:13.0710, lon:77.5820 },
  { id:"surge", name:"Surge", cat:"incubator", area:"cbd", prec:"city",
    blurb:"Peak XV's rapid-scale-up programme for early founders.", backers:[] },
  { id:"axilor", name:"Axilor Ventures", cat:"incubator", area:"cbd", prec:"city",
    blurb:"Accelerator and seed fund set up by Infosys co-founders.", backers:[] },
  { id:"gfs", name:"Google for Startups Accelerator", cat:"incubator", area:"cbd", prec:"city",
    blurb:"Google's accelerator for Indian startups.", backers:[] },

  // ── Tech parks
  { id:"manyata", name:"Manyata Embassy Business Park", cat:"techpark", area:"manyata", prec:"area",
    blurb:"One of the city's largest office parks, on the northern stretch of the Outer Ring Road.", backers:[], lat:13.0450, lon:77.6200 },
  { id:"itpl", name:"ITPL", cat:"techpark", area:"whitefield", prec:"area", year:1994,
    blurb:"International Tech Park, Whitefield. It turned a village of orchards into an IT suburb.", backers:[], lat:12.9857, lon:77.7310 },
  { id:"etv", name:"Embassy Tech Village", cat:"techpark", area:"orr", prec:"area",
    blurb:"The campus on the ORR where Flipkart and Swiggy are based.", backers:[], lat:12.9311, lon:77.6905 },
  { id:"ecospace", name:"RMZ Ecospace", cat:"techpark", area:"orr", prec:"area",
    blurb:"Office campus near Bellandur on the Outer Ring Road.", backers:[], lat:12.9250, lon:77.6830 },
  { id:"bagmane", name:"Bagmane Tech Park", cat:"techpark", area:"cvraman", prec:"area",
    blurb:"Office park in CV Raman Nagar.", backers:[], lat:12.9806, lon:77.6621 },
  { id:"egl", name:"Embassy GolfLinks", cat:"techpark", area:"domlur", prec:"area",
    blurb:"Office campus around a golf course, off Intermediate Ring Road.", backers:[], lat:12.9540, lon:77.6440 },
  { id:"ptp", name:"Prestige Tech Park", cat:"techpark", area:"marathahalli", prec:"area",
    blurb:"Office park at Kadubeesanahalli on the ORR.", backers:[], lat:12.9400, lon:77.6960 },
  { id:"gvtp", name:"Global Village Tech Park", cat:"techpark", area:"mysoreroad", prec:"area",
    blurb:"Office campus off Mysore Road.", backers:[], lat:12.9200, lon:77.4990 },
  { id:"ecitypark", name:"Electronic City", cat:"techpark", area:"ecity", prec:"area",
    blurb:"The city's original IT township, begun in 1978. Infosys, Biocon and others are here.", backers:[], lat:12.8452, lon:77.6602 },

  // ── Coworking
  { id:"91sb", name:"91springboard", cat:"cowork", area:"koramangala", prec:"area", blurb:"Coworking chain with Koramangala hubs.", backers:[] },
  { id:"bhive", name:"BHIVE", cat:"cowork", area:"hsr", prec:"area", blurb:"Bengaluru-born coworking, started in HSR Layout.", backers:[] },
  { id:"wework", name:"WeWork Galaxy", cat:"cowork", area:"cbd", prec:"area", blurb:"Coworking on Residency Road.", backers:[] },
  { id:"indiqube", name:"IndiQube", cat:"cowork", area:"orr", prec:"city", blurb:"Bengaluru-headquartered managed offices.", backers:[] },

  // ── Global R&D & corporates
  { id:"infosys", name:"Infosys", cat:"corporate", area:"ecity", prec:"area", year:1981,
    blurb:"Founded in Pune in 1981, moved to Bengaluru in 1983. Its Electronic City campus, with the glass pyramid, is a city landmark.", backers:[], lat:12.8412, lon:77.6642 },
  { id:"wipro", name:"Wipro", cat:"corporate", area:"sarjapur", prec:"area", year:1945,
    blurb:"Began as a vegetable oil company; now an IT services giant headquartered on Sarjapur Road.", backers:[], lat:12.9160, lon:77.6860 },
  { id:"biocon", name:"Biocon", cat:"corporate", area:"ecity", prec:"area", year:1978,
    blurb:"Biotech founded by Kiran Mazumdar-Shaw in a Koramangala garage.", backers:[], lat:12.8340, lon:77.6720 },
  { id:"titan", name:"Titan", cat:"corporate", area:"ecity", prec:"area", year:1984,
    blurb:"Watches and jewellery, a Tata company headquartered near Electronic City.", backers:[], lat:12.8480, lon:77.6720 },
  { id:"googlein", name:"Google · Ananta", cat:"corporate", area:"krpuram", prec:"area",
    blurb:"Google's large Bengaluru campus in Mahadevapura.", backers:[], lat:12.9950, lon:77.6980 },
  { id:"sap", name:"SAP Labs India", cat:"corporate", area:"whitefield", prec:"area",
    blurb:"SAP's large R&D centre in Whitefield.", backers:[], lat:12.9780, lon:77.7150 },
  { id:"amazonwtc", name:"Amazon · WTC", cat:"corporate", area:"malleshwaram", prec:"area",
    blurb:"Offices in the World Trade Center at Brigade Gateway.", backers:[], lat:13.0127, lon:77.5550 },
  { id:"microsoft", name:"Microsoft IDC", cat:"corporate", area:"domlur", prec:"area",
    blurb:"India Development Center, one of Microsoft's largest outside Redmond.", backers:[], lat:12.9560, lon:77.6460 },
  { id:"cisco", name:"Cisco", cat:"corporate", area:"marathahalli", prec:"area",
    blurb:"Large engineering campus at Kadubeesanahalli.", backers:[], lat:12.9360, lon:77.6990 },
  { id:"intel", name:"Intel India", cat:"corporate", area:"orr", prec:"area",
    blurb:"Design centre off the ORR at Devarabeesanahalli.", backers:[], lat:12.9370, lon:77.6870 },

  // ── Public bodies
  { id:"isro", name:"ISRO HQ", cat:"public", area:"hebbal", prec:"area", year:1969,
    blurb:"Antariksh Bhavan on New BEL Road. Chandrayaan-3's landing was watched from here.", backers:[], lat:13.03624, lon:77.57101 },
  { id:"hal", name:"HAL", cat:"public", area:"oldairport", prec:"area", year:1940,
    blurb:"Hindustan Aeronautics. Its airfield was Bengaluru's airport until 2008.", backers:[], lat:12.9560, lon:77.6680 },
  { id:"bel", name:"BEL", cat:"public", area:"jalahalli", prec:"area", year:1954,
    blurb:"Bharat Electronics, the defence electronics maker in Jalahalli.", backers:[], lat:13.0450, lon:77.5450 },
  { id:"kdem", name:"Karnataka Digital Economy Mission", cat:"public", area:"cbd", prec:"city",
    blurb:"State body behind 'Beyond Bengaluru' and startup programmes.", backers:[] },
  { id:"startupkarnataka", name:"Startup Karnataka", cat:"public", area:"cbd", prec:"city",
    blurb:"The state's startup cell, run through KITS.", backers:[] },
];

// Landmarks built as custom models. `kind` picks the builder in world.js.
NO.LANDMARKS = [
  { id:"vidhana", kind:"vidhana", name:"Vidhana Soudha", lat:12.97975, lon:77.59062, egg:"soudha",
    text:"Seat of the state legislature, completed in 1956 in Neo-Dravidian style. The inscription over its entrance says Government's work is God's work." },
  { id:"highcourt", kind:"attara", name:"Attara Kacheri", lat:12.97789, lon:77.59267,
    text:"The red High Court building at the edge of Cubbon Park." },
  { id:"library", kind:"library", name:"Seshadri Iyer Memorial Hall", lat:12.97435, lon:77.59059,
    text:"The red State Central Library inside Cubbon Park." },
  { id:"palace", kind:"palace", name:"Bangalore Palace", lat:12.9987, lon:77.5921,
    text:"Tudor-style palace of the Wadiyars, finished in 1887 and said to be modelled on Windsor Castle." },
  { id:"glasshouse", kind:"glasshouse", name:"Lalbagh Glass House", lat:12.9502, lon:77.5850, egg:"flowers",
    text:"Built in 1889 on the lines of London's Crystal Palace. The flower show runs around Republic Day and Independence Day." },
  { id:"kgtower", kind:"kgtower", name:"Kempegowda Tower, Lalbagh", lat:12.9455, lon:77.5870,
    text:"One of four watchtowers said to mark the limits of the city founded by Kempegowda in 1537." },
  { id:"ubcity", kind:"ubcity", name:"UB City", lat:12.97186, lon:77.59567,
    text:"Luxury mall and office towers off Vittal Mallya Road." },
  { id:"stadium", kind:"stadium", name:"M. Chinnaswamy Stadium", lat:12.9788, lon:77.5996, egg:"cup",
    text:"Home of Royal Challengers Bengaluru. After 17 seasons of 'Ee Sala Cup Namde', RCB won the IPL in 2025." },
  { id:"iskcon", kind:"iskcon", name:"ISKCON Temple", lat:13.0098, lon:77.5511,
    text:"Hilltop temple in Rajajinagar, opened in 1997." },
  { id:"bulltemple", kind:"nandi", name:"Dodda Basavana Gudi", lat:12.9423, lon:77.5681, egg:"nandi",
    text:"The Bull Temple in Basavanagudi, with a monolithic Nandi. The groundnut fair (Kadalekai Parishe) is held nearby every November." },
  { id:"tipu", kind:"tipu", name:"Tipu Sultan's Summer Palace", lat:12.9594, lon:77.5737,
    text:"Two-storey teak palace completed in 1791." },
  { id:"isro", kind:"rocket", name:"ISRO · Antariksh Bhavan", lat:13.03624, lon:77.57101, egg:"rocket",
    text:"Headquarters of the Indian Space Research Organisation." },
  { id:"infy", kind:"pyramid", name:"Infosys Campus", lat:12.8450, lon:77.6640,
    text:"The glass pyramid is Electronic City's best-known building." },
  { id:"silkboard", kind:"silkboard", name:"Silk Board Junction", lat:12.91604, lon:77.62391, egg:"silkboard",
    text:"Where Hosur Road meets the Outer Ring Road, and where Bengaluru's traffic is at its worst." },
  { id:"bellandur", kind:"foam", name:"Bellandur Lake", lat:12.93714, lon:77.67202, egg:"foam",
    text:"The city's largest lake, famous for sewage-driven froth that drifted onto roads and once caught fire in 2015." },
  { id:"wtc", kind:"tower", name:"World Trade Center", lat:13.01236, lon:77.55643,
    text:"Brigade Gateway's 32-storey tower in Malleshwaram." },
  { id:"majestic", kind:"busstand", name:"Kempegowda Bus Station", lat:12.97818, lon:77.57219,
    text:"Majestic, where BMTC and KSRTC buses meet the metro interchange." },
  { id:"mtr", kind:"darshini", name:"MTR, Lalbagh Road", lat:12.9555, lon:77.5855, egg:"coffee",
    text:"Mavalli Tiffin Rooms, serving since 1924. Rava idli is said to have been invented here during wartime rice shortages." },
  { id:"vb", kind:"darshini", name:"Vidyarthi Bhavan", lat:12.9453, lon:77.5712, egg:"dosa",
    text:"Basavanagudi's dosa institution since 1943. Waiters carry around 16 plates stacked up one arm." },
  { id:"hebbalflyover", kind:"sign", name:"Hebbal Flyover", lat:13.04086, lon:77.5898,
    text:"The gateway to the airport road." },
];

// Kannada, one phrase at a time.
NO.KANNADA = [
  ["ನಮಸ್ಕಾರ", "Namaskara", "Hello"],
  ["ಊಟ ಆಯ್ತಾ?", "Oota aytha?", "Had your meal? (how people say hello)"],
  ["ಸ್ವಲ್ಪ ಅಡ್ಜಸ್ಟ್ ಮಾಡಿ", "Swalpa adjust maadi", "Please adjust a little. The city motto."],
  ["ಗುರು", "Guru", "Boss / bro. Works on anyone."],
  ["ಮಗಾ", "Maga", "Buddy (literally, son)"],
  ["ಸಕ್ಕತ್", "Sakkath", "Awesome"],
  ["ಗೊತ್ತಿಲ್ಲ", "Gottilla", "I don't know"],
  ["ಬೇಕು / ಬೇಡ", "Beku / Beda", "Want / don't want"],
  ["ಎಷ್ಟು?", "Eshtu?", "How much?"],
  ["ಹೌದು / ಇಲ್ಲ", "Houdu / Illa", "Yes / no"],
  ["ಬನ್ನಿ", "Banni", "Please come (in)"],
  ["ಹೇಗಿದ್ದೀರಾ?", "Hegiddira?", "How are you?"],
  ["ಮೀಟರ್ ಹಾಕಿ", "Meter haaki", "Please put the meter on"],
  ["ನೇರವಾಗಿ ಹೋಗಿ", "Neravagi hogi", "Go straight"],
];

NO.LOADING = [
  "Negotiating with an auto driver",
  "Waiting at Silk Board",
  "Brewing filter coffee",
  "Checking if it rains at 4 pm",
  "Finding parking in Indiranagar",
  "Asking the metro to come faster",
  "Adjusting swalpa",
  "Counting rooftop water tanks",
  "Pitching to a VC in Koramangala",
  "Planting a few more rain trees",
];

NO.AUTO_LINES = [
  "Meter? Illa saar. 50 rupees extra.",
  "Koramangala? That side won't come, saar.",
  "Return trip empty, saar. Please adjust.",
  "One and a half, saar. Night charge.",
  "Silk Board? Madam, you'll be there till Diwali.",
  "Only via Rapido rate, saar.",
  "Barthini, barthini. Kootkoli. (Coming, coming. Sit down.)",
];

NO.EGGS = {
  silkboard: "Stuck at Silk Board",
  foam:      "Bellandur foam",
  cup:       "Ee Sala Cup Namde",
  rocket:    "Launch from Antariksh Bhavan",
  auto:      "Auto negotiation",
  cow:       "Right of way",
  rain:      "4 pm rain",
  konami:    "Zero-traffic dream",
  soudha:    "Government's work",
  coffee:    "Filter coffee",
  dosa:      "Sixteen dosas, one arm",
  adjust:    "Swalpa adjust maadi",
  startup:   "Third floor above a café",
  plane:     "The airport commute",
  nandi:     "Kadalekai Parishe",
  flowers:   "Lalbagh flower show",
  metro:     "Namma Metro",
  dog:       "Street dog union",
};
